# Generated by Django 5.2.12 on 2026-03-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=16)),
                ('module', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('platform', models.CharField(blank=True, max_length=64, null=True)),
                ('message', models.TextField()),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('job_url', models.TextField(blank=True, null=True)),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=16)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='core_syslog_time_idx'), models.Index(fields=['level'], name='core_syslog_level_idx'), models.Index(fields=['module'], name='core_syslog_module_idx'), models.Index(fields=['status'], name='core_syslog_status_idx')],
            },
        ),
    ]
