# Generated by Django 5.2.12 on 2026-03-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('contract', 'Contract'), ('full_time', 'Full Time'), ('part_time', 'Part Time'), ('freelance', 'Freelance')], default='contract', max_length=32),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
