# Generated by Django 5.2.12 on 2026-03-16 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_job_company_job_job_type_job_skills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserJobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.IntegerField()),
                ('proposal_text', models.TextField(blank=True, null=True)),
                ('application_status', models.CharField(choices=[('not_applied', 'Not Applied'), ('auto_applied', 'Auto Applied'), ('manual_apply_required', 'Manual Apply Required')], default='not_applied', max_length=32)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_matches', to='core.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-match_score', '-created_at'],
                'indexes': [models.Index(fields=['user'], name='core_match_user_idx'), models.Index(fields=['job'], name='core_match_job_idx'), models.Index(fields=['match_score'], name='core_match_score_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'job'), name='core_unique_user_job_match')],
            },
        ),
    ]
