# Generated by Django 5.2.12 on 2026-03-17 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_telegram_chat_id_telegramverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramverification',
            name='chat_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='telegramverification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='telegramverification',
            index=models.Index(fields=['chat_id'], name='core_telegram_chat_idx'),
        ),
    ]
