# Generated by Django 5.2.12 on 2026-03-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_telegramverification_chat_id_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="job",
            name="core_unique_job_url",
        ),
        migrations.AlterField(
            model_name="job",
            name="platform",
            field=models.CharField(
                choices=[
                    ("upwork", "Upwork"),
                    ("mercor", "Mercor"),
                    ("outlier", "Outlier"),
                    ("remoteok", "RemoteOK"),
                    ("linkedin", "LinkedIn"),
                    ("naukri", "Naukri"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_url",
            field=models.URLField(max_length=1000, unique=True),
        ),
    ]
