# Generated by Django 5.2.12 on 2026-03-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_job_url_unique_and_naukri_platform"),
    ]

    operations = [
        migrations.CreateModel(
            name="SerpAPIUsage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(unique=True)),
                ("month", models.CharField(db_index=True, max_length=7)),
                ("request_count", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["date"], name="core_serpapi_date_idx"),
                    models.Index(fields=["month"], name="core_serpapi_month_idx"),
                ],
            },
        ),
    ]
